name: Deploy Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS # Sometimes we don't need this step if the runner already has it installed
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # installing a clean install of devDependencies
      - name: Run tests
        run: npm run lint
  test:
    needs: lint # This makes this job run in sequential after the job "lint" and not in parallel
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS # Sometimes we don't need this step if the runner already has it installed
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # installing a clean install of devDependencies
      - name: Run tests
        run: npm run test
  deploy:
    needs: test # This makes this job run in sequential after the job "test" and not in parallel
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS # Sometimes we don't need this step if the runner already has it installed
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # installing a clean install of devDependencies
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..." # In this step we should deploy to a hosting server, here we are just simulating